Repository k-bialucha/react-native-playground, pull requests merged in 2019-10, with the labels that each got.

#1 Codestyle and Readme
  .editorconfig
  .eslintrc.js
  .prettierignore
  .prettierrc
  README.md
  package-lock.json
  package.json
Labels: setup

#2 Basic app navigation
  .eslintrc.js
  App.tsx
  package-lock.json
  package.json
  screens/Home.tsx
  screens/Todos.tsx
Labels: feature

#3 Basic Todos implementation | ESLint config adjustments
  .eslintrc.js
  App.tsx
  components/Todo/Item.tsx
  components/Todo/List.tsx
  models/Todo.ts
  screens/Todos.tsx
Labels: feature, setup

#4 Added types to Todos screen component
  screens/Todos.tsx
Labels: enhancement
